---
name: Linting

on:
    push:
        branches: [main, beta, lint-2]
    pull_request:
        branches: [main, beta]

        #thing
jobs:
    luacheck:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - name: Run luacheck
              uses: ./.github/actions/luacheck/
